// <auto-generated />
namespace RecurringThings.PostgreSQL.Migrations;

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecurringThings.PostgreSQL.Data;

#nullable disable

[DbContext(typeof(RecurringThingsDbContext))]
[Migration("20260127200000_AddMonthDayBehavior")]
partial class AddMonthDayBehavior
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("RecurringThings.PostgreSQL.Data.Entities.OccurrenceEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<TimeSpan>("Duration")
                    .HasColumnType("interval")
                    .HasColumnName("duration");

                b.Property<DateTime>("EndTime")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("end_time");

                b.Property<string>("Extensions")
                    .HasColumnType("jsonb")
                    .HasColumnName("extensions");

                b.Property<string>("Organization")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("organization");

                b.Property<string>("ResourcePath")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("resource_path");

                b.Property<DateTime>("StartTime")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("start_time");

                b.Property<string>("TimeZone")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("time_zone");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("type");

                b.HasKey("Id");

                b.HasIndex("Organization", "ResourcePath", "Type", "StartTime", "EndTime")
                    .HasDatabaseName("idx_occurrences_query");

                b.ToTable("occurrences");
            });

        modelBuilder.Entity("RecurringThings.PostgreSQL.Data.Entities.OccurrenceExceptionEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Extensions")
                    .HasColumnType("jsonb")
                    .HasColumnName("extensions");

                b.Property<string>("Organization")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("organization");

                b.Property<DateTime>("OriginalTimeUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("original_time_utc");

                b.Property<Guid>("RecurrenceId")
                    .HasColumnType("uuid")
                    .HasColumnName("recurrence_id");

                b.Property<string>("ResourcePath")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("resource_path");

                b.HasKey("Id");

                b.HasIndex("RecurrenceId")
                    .HasDatabaseName("idx_exceptions_recurrence");

                b.HasIndex("Organization", "ResourcePath", "OriginalTimeUtc")
                    .HasDatabaseName("idx_exceptions_query");

                b.ToTable("occurrence_exceptions");
            });

        modelBuilder.Entity("RecurringThings.PostgreSQL.Data.Entities.OccurrenceOverrideEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<TimeSpan>("Duration")
                    .HasColumnType("interval")
                    .HasColumnName("duration");

                b.Property<DateTime>("EndTime")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("end_time");

                b.Property<string>("Extensions")
                    .HasColumnType("jsonb")
                    .HasColumnName("extensions");

                b.Property<string>("Organization")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("organization");

                b.Property<TimeSpan>("OriginalDuration")
                    .HasColumnType("interval")
                    .HasColumnName("original_duration");

                b.Property<string>("OriginalExtensions")
                    .HasColumnType("jsonb")
                    .HasColumnName("original_extensions");

                b.Property<DateTime>("OriginalTimeUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("original_time_utc");

                b.Property<Guid>("RecurrenceId")
                    .HasColumnType("uuid")
                    .HasColumnName("recurrence_id");

                b.Property<string>("ResourcePath")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("resource_path");

                b.Property<DateTime>("StartTime")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("start_time");

                b.HasKey("Id");

                b.HasIndex("RecurrenceId")
                    .HasDatabaseName("idx_overrides_recurrence");

                b.HasIndex("Organization", "ResourcePath", "OriginalTimeUtc")
                    .HasDatabaseName("idx_overrides_original");

                b.HasIndex("Organization", "ResourcePath", "StartTime", "EndTime")
                    .HasDatabaseName("idx_overrides_start");

                b.ToTable("occurrence_overrides");
            });

        modelBuilder.Entity("RecurringThings.PostgreSQL.Data.Entities.RecurrenceEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<TimeSpan>("Duration")
                    .HasColumnType("interval")
                    .HasColumnName("duration");

                b.Property<string>("Extensions")
                    .HasColumnType("jsonb")
                    .HasColumnName("extensions");

                b.Property<string>("MonthDayBehavior")
                    .HasMaxLength(10)
                    .HasColumnType("character varying(10)")
                    .HasColumnName("month_day_behavior");

                b.Property<string>("Organization")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("organization");

                b.Property<string>("RRule")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)")
                    .HasColumnName("r_rule");

                b.Property<DateTime>("RecurrenceEndTime")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("recurrence_end_time");

                b.Property<string>("ResourcePath")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("resource_path");

                b.Property<DateTime>("StartTime")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("start_time");

                b.Property<string>("TimeZone")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("time_zone");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("type");

                b.HasKey("Id");

                b.HasIndex("Organization", "ResourcePath", "Type", "StartTime", "RecurrenceEndTime")
                    .HasDatabaseName("idx_recurrences_query");

                b.ToTable("recurrences");
            });

        modelBuilder.Entity("RecurringThings.PostgreSQL.Data.Entities.OccurrenceExceptionEntity", b =>
            {
                b.HasOne("RecurringThings.PostgreSQL.Data.Entities.RecurrenceEntity", "Recurrence")
                    .WithMany("Exceptions")
                    .HasForeignKey("RecurrenceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Recurrence");
            });

        modelBuilder.Entity("RecurringThings.PostgreSQL.Data.Entities.OccurrenceOverrideEntity", b =>
            {
                b.HasOne("RecurringThings.PostgreSQL.Data.Entities.RecurrenceEntity", "Recurrence")
                    .WithMany("Overrides")
                    .HasForeignKey("RecurrenceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Recurrence");
            });

        modelBuilder.Entity("RecurringThings.PostgreSQL.Data.Entities.RecurrenceEntity", b =>
            {
                b.Navigation("Exceptions");

                b.Navigation("Overrides");
            });
#pragma warning restore 612, 618
    }
}
