namespace RecurringThings.Domain;

using System;
using System.Collections.Generic;

/// <summary>
/// Represents a modification of a specific virtualized occurrence from a recurrence.
/// </summary>
/// <remarks>
/// <para>
/// When an override exists, it replaces the matching virtualized occurrence
/// (identified by <see cref="OriginalTimeUtc"/>) with the override's values.
/// </para>
/// <para>
/// Original values are denormalized at creation time to support showing "before and after" changes.
/// TimeZone is inherited from the parent recurrence and not stored separately.
/// </para>
/// <para>
/// After creation, <see cref="StartTime"/>, <see cref="Duration"/>, and <see cref="Extensions"/> can be modified.
/// When StartTime or Duration changes, <see cref="EndTime"/> is automatically recomputed.
/// </para>
/// </remarks>
internal sealed class OccurrenceOverride
{
    private DateTime _startTime;
    private TimeSpan _duration;

    /// <summary>
    /// Gets the unique identifier for this override.
    /// </summary>
    public Guid Id { get; init; }

    /// <summary>
    /// Gets the tenant identifier for multi-tenant isolation.
    /// </summary>
    /// <remarks>
    /// Must match the Organization of the parent <see cref="Recurrence"/>.
    /// </remarks>
    public required string Organization { get; init; }

    /// <summary>
    /// Gets the hierarchical resource scope.
    /// </summary>
    /// <remarks>
    /// Must match the ResourcePath of the parent <see cref="Recurrence"/>.
    /// </remarks>
    public required string ResourcePath { get; init; }

    /// <summary>
    /// Gets the identifier of the parent recurrence.
    /// </summary>
    public Guid RecurrenceId { get; init; }

    /// <summary>
    /// Gets the UTC timestamp of the original occurrence being replaced.
    /// </summary>
    /// <remarks>
    /// This must exactly match the start time of a virtualized occurrence
    /// generated by the parent recurrence's RRule pattern.
    /// </remarks>
    public DateTime OriginalTimeUtc { get; init; }

    /// <summary>
    /// Gets or sets the new UTC timestamp when this occurrence starts.
    /// </summary>
    /// <remarks>
    /// When modified, <see cref="EndTime"/> is automatically recomputed.
    /// Can differ from <see cref="OriginalTimeUtc"/> to "move" the occurrence.
    /// </remarks>
    public DateTime StartTime
    {
        get => _startTime;
        set
        {
            _startTime = value;
            EndTime = _startTime + _duration;
        }
    }

    /// <summary>
    /// Gets the UTC timestamp when this occurrence ends.
    /// </summary>
    /// <remarks>
    /// This value is computed as <see cref="StartTime"/> + <see cref="Duration"/>.
    /// It is automatically recomputed when StartTime or Duration changes.
    /// </remarks>
    public DateTime EndTime { get; private set; }

    /// <summary>
    /// Gets or sets the new duration of this occurrence.
    /// </summary>
    /// <remarks>
    /// When modified, <see cref="EndTime"/> is automatically recomputed.
    /// </remarks>
    public TimeSpan Duration
    {
        get => _duration;
        set
        {
            _duration = value;
            EndTime = _startTime + _duration;
        }
    }

    /// <summary>
    /// Gets the original duration from the parent recurrence at the time the override was created.
    /// </summary>
    /// <remarks>
    /// Denormalized to support showing the original values before the override was applied.
    /// </remarks>
    public TimeSpan OriginalDuration { get; init; }

    /// <summary>
    /// Gets the original extensions from the parent recurrence at the time the override was created.
    /// </summary>
    /// <remarks>
    /// Denormalized to support showing the original values before the override was applied.
    /// </remarks>
    public Dictionary<string, string>? OriginalExtensions { get; init; }

    /// <summary>
    /// Gets or sets the user-defined key-value metadata.
    /// </summary>
    /// <remarks>
    /// <para>Key constraints: 1-100 characters, non-null.</para>
    /// <para>Value constraints: 0-1024 characters, non-null.</para>
    /// </remarks>
    public Dictionary<string, string>? Extensions { get; set; }

    /// <summary>
    /// Initializes the override with computed EndTime.
    /// </summary>
    /// <param name="startTime">The UTC start time.</param>
    /// <param name="duration">The duration of the occurrence.</param>
    public void Initialize(DateTime startTime, TimeSpan duration)
    {
        _startTime = startTime;
        _duration = duration;
        EndTime = _startTime + _duration;
    }
}
