namespace RecurringThings.Domain;

using System;
using System.Collections.Generic;

/// <summary>
/// Represents a cancellation of a specific virtualized occurrence from a recurrence.
/// </summary>
/// <remarks>
/// <para>
/// When an occurrence exception exists, the matching virtualized occurrence
/// (identified by <see cref="OriginalTimeUtc"/>) is excluded from query results.
/// </para>
/// <para>
/// An occurrence cannot have both an exception and an override simultaneously.
/// Once an exception is created, the occurrence cannot be restored through the API.
/// </para>
/// </remarks>
internal sealed class OccurrenceException
{
    /// <summary>
    /// Gets the unique identifier for this exception.
    /// </summary>
    public Guid Id { get; init; }

    /// <summary>
    /// Gets the tenant identifier for multi-tenant isolation.
    /// </summary>
    /// <remarks>
    /// Must match the Organization of the parent <see cref="Recurrence"/>.
    /// </remarks>
    public required string Organization { get; init; }

    /// <summary>
    /// Gets the hierarchical resource scope.
    /// </summary>
    /// <remarks>
    /// Must match the ResourcePath of the parent <see cref="Recurrence"/>.
    /// </remarks>
    public required string ResourcePath { get; init; }

    /// <summary>
    /// Gets the identifier of the parent recurrence.
    /// </summary>
    public Guid RecurrenceId { get; init; }

    /// <summary>
    /// Gets the UTC timestamp of the occurrence being cancelled.
    /// </summary>
    /// <remarks>
    /// This must exactly match the start time of a virtualized occurrence
    /// generated by the parent recurrence's RRule pattern.
    /// </remarks>
    public DateTime OriginalTimeUtc { get; init; }

    /// <summary>
    /// Gets or sets the user-defined key-value metadata.
    /// </summary>
    /// <remarks>
    /// <para>Key constraints: 1-100 characters, non-null.</para>
    /// <para>Value constraints: 0-1024 characters, non-null.</para>
    /// </remarks>
    public Dictionary<string, string>? Extensions { get; set; }
}
