namespace RecurringThings.Core;

using Domain;

/// <summary>
///     Provides methods to interacts with the occurrences.
/// </summary>
public interface IVirtualizationService
{

    /// <summary>
    ///     Gets the materialized occurrences between two dates.
    /// 
    ///     This method will join both occurrence generated by recurrences and
    ///     singular occurrences while handling exclusions and overrides.
    /// </summary>
    /// <param name="rangeStartUtc"></param>
    /// <param name="rangeEndUtc"></param>
    /// <param name="cancellationToken"></param>
    /// <returns></returns>
    Task<IReadOnlyList<VirtualizedOccurrence>> GetOccurrencesAsync(
        DateTime rangeStartUtc, 
        DateTime rangeEndUtc, 
        CancellationToken cancellationToken = default);

}
